[[quote]]
author = "Franklin D. Roosevelt"
text = "The only limit to our realization of tomorrow is our doubts of today."

[[quote]]
author = "Eleanor Roosevelt"
text = "The future belongs to those who believe in the beauty of their dreams."

[[quote]]
author = "Sam Levenson"
text = "Do not watch the clock; do what it does. Keep going."

[[quote]]
author = "William Penn"
text = "Time is what we want most, but what we use worst."

[[quote]]
author = "Albert Schweitzer"
text = "Success is not the key to happiness. Happiness is the key to success."

[[quote]]
text = "Fall down seven times, stand up eight."

[[quote]]
author = "Marthe Troly-Curtin"
text = "Time you enjoy wasting is not wasted time."

[[quote]]
author = "Mother Teresa"
text = "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin."

[[quote]]
author = "Coco Chanel"
text = "Don't spend time beating on a wall, hoping to transform it into a door."

[[quote]]
author = "Andy Warhol"
text = "They always say time changes things, but you actually have to change them yourself."
