clock_type = "ColorClock"
name = "Italic 7 Segment Display"

[config]
hour = """   /@@@@@@/     /@@@@@@/
  Θ        Θ   Θ        Θ
  @        @   @        @
 @        @   @        @
 Θ        Θ   Θ        Θ
  /@@@@@@/     /@@@@@@/
 Θ        Θ   Θ        Θ
 @        @   @        @
@        @   @        @
Θ        Θ   Θ        Θ
 /@@@@@@/     /@@@@@@/"""
minutes = """   /@@@@@@/     /@@@@@@/
  Θ        Θ   Θ        Θ
  @        @   @        @
 @        @   @        @
 Θ        Θ   Θ        Θ
  /@@@@@@/     /@@@@@@/
 Θ        Θ   Θ        Θ
 @        @   @        @
@        @   @        @
Θ        Θ   Θ        Θ
 /@@@@@@/     /@@@@@@/"""
seconds = """   /@@@@@@/     /@@@@@@/
  Θ        Θ   Θ        Θ
  @        @   @        @
 @        @   @        @
 Θ        Θ   Θ        Θ
  /@@@@@@/     /@@@@@@/
 Θ        Θ   Θ        Θ
 @        @   @        @
@        @   @        @
Θ        Θ   Θ        Θ
 /@@@@@@/     /@@@@@@/"""

seperator = """



{Θ}


{Θ}


"""
