clock_type = "ColorClock"
name = "7 Seven Segment"

[config]
hour = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""
minutes = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""
seconds = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""

seperator = """




(@)



(@)




"""
