clock_type = "ColorClock"

[config]
name = "7 Seven Segment"

hour = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""
minutes = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""
seconds = """ «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»
¡           ¡ ¡           ¡
@           @ @           @
#           # #           #
#           # #           #
@           @ @           @
!           ! !           !
 «<@#####@>»   «<@#####@>»"""

seperator = """




(@)



(@)




"""

hour_coords = [
]

minute_coords = [

]

second_coords = []

always_on_coords = []


format = "Hms"

# vim: set tabstop=2 shiftwidth=2 expandtab:
