clock_type = "ColorClock"

[config]
name = "Binary Temples"

hour = """              Θ
              |
         _,*/@@@\\,_
       ∙«≡≡≡≡«..»≡≡»∙
          ╟╧╧╧││╧╢
        Θ«╟╤╤╤││╤╢»Θ
    ∙,____╟╧╧╧││╧╢
  _,*@@@@@╟╤╤╤││╤╢»Θ
Θ≈≈≡≡≡≡≡≡≡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢»Θ
   ╟╪╪╪╪╪╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢
   ╙┴┴┴┴┴┘╙┴┴┴┴┴┴╜"""
minutes = """              Θ
              |
         _,*/@@@\\,_
       ∙«≡≡≡≡«..»≡≡»∙
          ╟╧╧╧││╧╢
    ∙,____╟╤╤╤││╤╢»Θ
  _,*@@@@@╟╧╧╧││╧╢
Θ≈≈≡≡≡≡≡≡≡╟╤╤╤││╤╢»Θ
   ╟╪╪╪╪╪╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢
   ╙┴┴┴┴┴┘╙┴┴┴┴┴┴╜"""
seconds = """              Θ
              |
         _,*/@@@\\,_
       ∙«≡≡≡≡«..»≡≡»∙
          ╟╧╧╧││╧╢
    ∙,____╟╤╤╤││╤╢»Θ
  _,*@@@@@╟╧╧╧││╧╢
Θ≈≈≡≡≡≡≡≡≡╟╤╤╤││╤╢»Θ
   ╟╪╪╪╪╪╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢
   ╙┴┴┴┴┴┘╙┴┴┴┴┴┴╜"""

render_mode = "bits"

hour_coords = [
  [[1, [[11, 1]]], [2, [[8, 0]]]],
  [
    [1, [[11, 19]]],
    [2, [[9, 19]]],
    [4, [[7, 19]]],
    [8, [[5, 19], [5, 8]]],
  ]
]

minute_coords = [
  [[1, [[11, 1]]], [2, [[9, 1]]], [4, [[7, 0]]]],
  [[1, [[11, 19]]], [2, [[9, 19]]], [4, [[7, 19]]], [8, [[5, 19]]]],
]

second_coords = [
  [[1, [[11, 1]]], [2, [[9, 1]]], [4, [[7, 0]]]],
  [[1, [[11, 19]]], [2, [[9, 19]]], [4, [[7, 19]]], [8, [[5, 19]]]],
]


always_on_coords = [[0, 14]]

format = "Hms"

# vim: set tabstop=2 shiftwidth=2 expandtab:
