clock_type = "ColorClock"
name = "Thermometer"

[config]
hour = """   ╭─╮ °C
12 ┤█│
   ┤█│
 9 ┤█│
   ┤█│
   ┤█│
 7 ┤█│
   ┤█│
   ┤█│
 4 ┤█│
   ┤█│
   ┤█│
 1 ┤█│
   ╰─╯"""
minutes = """   ╭─╮ °F
60 ┤█│
   ┤█│
45 ┤█│
   ┤█│
   ┤█│
35 ┤█│
   ┤█│
   ┤█│
20 ┤█│
   ┤█│
   ┤█│
 5 ┤█│
   ╰─╯"""
seconds = """   ╭─╮ °F
60 ┤█│
   ┤█│
45 ┤█│
   ┤█│
   ┤█│
35 ┤█│
   ┤█│
   ┤█│
20 ┤█│
   ┤█│
   ┤█│
 5 ┤█│
   ╰─╯"""
