clock_type = "ColorClock"

[config]
name = "Thermometer"

hour = """   ╭─╮ °C
12 ┤█│
   ┤█│
 9 ┤█│
   ┤█│
   ┤█│
 7 ┤█│
   ┤█│
   ┤█│
 4 ┤█│
   ┤█│
   ┤█│
 1 ┤█│
   ╰─╯"""
minutes = """   ╭─╮ °F
60 ┤█│
   ┤█│
45 ┤█│
   ┤█│
   ┤█│
35 ┤█│
   ┤█│
   ┤█│
20 ┤█│
   ┤█│
   ┤█│
 5 ┤█│
   ╰─╯"""
seconds = """   ╭─╮ °F
60 ┤█│
   ┤█│
45 ┤█│
   ┤█│
   ┤█│
35 ┤█│
   ┤█│
   ┤█│
20 ┤█│
   ┤█│
   ┤█│
 5 ┤█│
   ╰─╯"""

display_mode = "gauge" # this will change the stuff that we need to pass in the config
clock_hour_amount = 12 # default 24 and these will be the only options

hour_coords = [
]

minute_coords = [

]

second_coords = []

always_on_coords = []


format = "Hms"

# vim: set tabstop=2 shiftwidth=2 expandtab:
