[package]
name = "tc-user_config_loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "check-config"
path = "src/bin/check_config.rs"

[dependencies]
tc-models            = { path = "../tc-models/" }

# External dependencies
clap                 = { workspace = true }
ratatui              = { workspace = true }
chrono               = { workspace = true }
toml                 = { workspace = true }
serde                = { workspace = true }
