[clock]
type="color_clock"

[hour]
ascii_art="""              Θ
              |
         _,*/@@@\,_
       ∙«≡≡≡≡«..»≡≡»∙
          ╟╧╧╧││╧╢
        Θ«╟╤╤╤││╤╢»Θ
    ∙,____╟╧╧╧││╧╢
  _,*@@@@@╟╤╤╤││╤╢»Θ
Θ≈≈≡≡≡≡≡≡≡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢»Θ
   ╟╪╪╪╪╪╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢
   ╙┴┴┴┴┴┘╙┴┴┴┴┴┴╜"""

[minutes + seconds]
ascii_art="""              Θ
              |
         _,*/@@@\,_
       ∙«≡≡≡≡«..»≡≡»∙
          ╟╧╧╧││╧╢
    ∙,____╟╤╤╤││╤╢»Θ
  _,*@@@@@╟╧╧╧││╧╢
Θ≈≈≡≡≡≡≡≡≡╟╤╤╤││╤╢»Θ
   ╟╪╪╪╪╪╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
 Θ«╟╧╧╧╧╧╡╟╤╤╤││╤╢»Θ
   ╟╤╤╤╤╤╡╟╧╧╧││╧╢
   ╟╪╪╪╪╪╡╟╤╤╤││╤╢
   ╙┴┴┴┴┴┘╙┴┴┴┴┴┴╜
"""

# specify coords somewhere
