clock_type = "ColorClock"

[config]
name = "Minimal Binary"

hour = """ @
 @
#@
#@"""

minutes = """ [
][
][
]["""

seconds = """ Θ
0Θ
0Θ
0Θ"""

separator = " "

render_mode = "bits"

[config.mapping]
symbols = { "@" = "Hours", "#" = "HourTens", "[" = "Minutes", "]" = "MinuteTens", "Θ" = "Seconds", "0" = "SecondTens" }

always_on_coords = []

clock_color = "#444444"

format = "HH:MM:SS"

# vim: set tabstop=2 shiftwidth=2 expandtab:
