name: CI (Rust + Nix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Nightly Toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt

    - name: Format check
      if: "!contains(github.event.pull_request.labels.*.name, 'skip-fmt')"
      run: cargo +nightly fmt --check

    - name: Clippy
      if: "!contains(github.event.pull_request.labels.*.name, 'skip-clippy')"
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Test
      if: "!contains(github.event.pull_request.labels.*.name, 'skip-tests')"
      run: cargo test --verbose

  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install Nix
      run: sh <(curl -L https://nixos.org/nix/install) --no-daemon

    - name: Flake check
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        nix flake check
